name: Generate GIF
on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          pip install snake wand numpy python-dotenv requests pygame
          cwd

      - name: Run Python Script
        uses: jannekem/run-python-script-action@v1.3
        env:
          ACCESS_TOKEN: ${{ secrets.SuperSecret }}
        with:
          script: ./src/main.py
