name: Generate GIF
on:
  schedule:
  - cron: "0 13 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Run Python Script
        uses: jannekem/run-python-script-action@v1.3
        with:
          script: /src/main.py
