name: Generate GIF
on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          auto-activate-base: false
      - run: |
          conda create -n snake wand numpy python-dotenv requests -c conda-forge && conda activate snake && pip install pygame

      - name: Run Python Script
        uses: jannekem/run-python-script-action@v1.3
        env:
          ACCESS_TOKEN: ${{ secrets.SuperSecret }}
        with:
          script: /src/main.py
